---
name: "CDK Workflow"
on:
  workflow_call:
    inputs:
      iam-role:
        required: true
        type: string
      cdk-stack:
        required: true
        type: string

jobs:
  cdk:
    name: Run cdk synth/deploy
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install
        working-directory: cdk

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ inputs.iam-role }}
          aws-region: us-east-1

      - name: Run cdk synth
        run: |
          npx cdk synth ${{ inputs.cdk-stack }}-us-east-1
          find cdk.out -type d -exec chmod 0755 {} \;
        working-directory: cdk

      - name: Run cdk diff
        run: |
          npx cdk diff -c aws-cdk:enableDiffNoFail=true --no-color --app cdk.out "${{ inputs.cdk-stack }}-us-east-1"  2>&1 | tee cdk.log
        working-directory: cdk

      - name: PR Comment
        if: ${{ github.event_name == 'pull_request' }}
        env:
          PR_NUMBER: ${{ github.event.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr comment $PR_NUMBER -F <(sed '1s/^/```\n/;$a```' cdk.log)
        working-directory: cdk

      - name: Deploy to ${{ inputs.cdk-stack }}
        if: ${{ contains(fromJSON('["main"]'), github.ref_name)  && github.event_name == 'push' }}
        run: |
          npx cdk deploy "${{ inputs.cdk-stack }}-us-east-1" --require-approval never --progress events
        working-directory: cdk
